routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Auth::routes();

Route::resource('products', 'ProductController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name', 'price'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return redirect()->route('products.index');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->input('search');
        $products = DB::table('products')
                            ->orderBy('id', 'desc')
                            ->where('name', 'LIKE', '%'. $search. '%')
                            ->OrWhere('price', 'LIKE', '%'. $search. '%')
                            ->paginate(10);
        
        return view('products.index', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required',
        ],[
            'name.required' => 'The product name field is required!',
            'price.required' => 'The price field is required!',
        ]);
        Product::create($request->all());

        return redirect()->route('products.index')->with('success', 'Product created successfully!');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = DB::table('products')->find($id);
        return view('products.edit', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required',
        ],[
            'name.required' => 'The product name field is required!',
            'price.required' => 'The price field is required!',
        ]);
        $product->update($request->all());
        return redirect()->route('products.index')->with('success', 'Product was updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()->route('products.index')

                        ->with('success','Product deleted successfully');
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script src="https://use.fontawesome.com/dd4db6263d.js"></script>
</body>
</html>

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Product Information</h3>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <form action="{{ route('products.store') }}" method="POST" id="createProduct">
                        @csrf
                        @include('products.form')
                    </form>
                </div>
                <div class="card-footer">
                    <div class="pull-right">
                        <a href="{{ route('products.index') }}" class="btn btn-secondary btn-sm"><i class="fa fa-share fa-flip-horizontal fa-fw"></i>Back</a>
                        <button type="submit" class="btn btn-primary btn-sm" form="createProduct"><i class="fa fa-floppy-o fa-fw"></i>Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Edit Product Information</h3>
                </div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <form action="{{ route('products.update', $data->id) }}" method="POST" id="editProduct">
                        @csrf
                        @method('PUT')
                        @include('products.form')
                    </form>
                </div>
                <div class="card-footer">
                    <div class="pull-right">
                        <a href="{{ route('products.index') }}" class="btn btn-secondary btn-sm"><i class="fa fa-share fa-flip-horizontal fa-fw"></i>Back</a>
                        <button type="submit" class="btn btn-primary btn-sm" form="editProduct"><i class="fa fa-floppy-o fa-fw"></i>Save Changes</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/form.blade.php
<div class="form-group row">
    <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

    <div class="col-md-6">
        <input type="text" class="form-control" name="name" value="{{ $data->name ?? '' }}" id="name" placeholder="Enter product name">
        @if ($errors->has('name'))
            <span class="text-danger">{{ $errors->first('name') }}</span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label for="price" class="col-md-4 col-form-label text-md-right">Price</label>

    <div class="col-md-6">
        <input type="number" class="form-control" name="price" value="{{ $data->price ?? ''}}" id="price" placeholder="$" step="0.01">
        @if ($errors->has('price'))
            <span class="text-danger">{{ $errors->first('price') }}</span>
        @endif
    </div>
</div>

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <div class="card-tools">
                        <div class="pull-left">
                            <h3 class="card-title">Laravel</h3>
                        </div>
                        <div class="pull-right">
                            <a href="{{ route('products.create') }}" class="btn btn-primary btn-sm"><i class="fa fa-plus fa-fw"></i>Add new</a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                    <form>
                        <div class="col-md-4 offset-md-8">
                            <div class="input-group mb-2">
                                <input type="text" class="form-control" name="search" placeholder="Search" value="{{ request('search')}}" title="Resfresh">
                                <div class="input-group-prepend">
                                  <div class="input-group-text"><a href="{{ route('products.index') }}"><i class="fa fa-refresh"></i></a></div>
                                </div>
                                
                            </div>
                            
                        </div>
                    </form>
                    
                   @include('products.table')
                   <div class="pull-left">
                       Total: {{$products->total()}} records
                   </div>
                   <div class="pull-right">
                        {{ $products -> appends([
                            'search' => request('search'),
                            ])->links() }}
                   </div>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/modal-delete.blade.php
<div class="modal fade" id="modal-delete-{{ $list->id }}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><i class="fa fa-trash fa-fw"></i> Deleting Product</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure, you want to delete product id - ({{ $list->id }})?
        </div>
        <div class="modal-footer">
            <form action="{{ route('products.destroy', $list->id) }}" method="POST">
                @csrf
                @method('delete')
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Confirm</button>
            </form>
        </div>
      </div>
    </div>
  </div>

resources/views/products/table.blade.php
<div style="overflow-x: auto">
    <table class="table table-hover">
        <thead>
            <tr>
                <th style="text-align:center">ID</th>
                <th>Product Name</th>
                <th>Price</th>
                <th class="text-center" style="width: 160px"><div style="width: 100px"></div> Actions</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($products as $index => $list)
            <tr>
                <td style="text-align:center">{{ $products ->firstItem() + $index }}</td>
                <td>{{ $list->name }}</td>
                <td>{{ $list->price }}</td>
                <td class="text-center">
                    <a href="{{ route('products.show', $list->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i> Edit</a>
                    <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-delete-{{ $list->id }}"><i class="fa fa-trash"></i> Delete</button>
                    @include('products.modal-delete')
                </td>
            </tr>
            @empty
                <tr>
                    <td colspan="99" class="text-center">
                        No Product Found!
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</div>